<?php
use App\Models\CustomField;
use App\Models\Setting;
use App\Models\State;
use App\Models\TrackLog;
use App\Models\User;
use App\Models\SaveJobLog; 
use Illuminate\Support\Str;
function supersetting($key, $default = '')
{
    $setting = Setting::where(['user_id' => 1, 'key' => $key])->first();
    $value   = $setting->value ?? $default;
    return $value;
}
function loginUser()
{
    return auth()->user() ?? null;
}
if (!function_exists('formatLog')) {
    function formatLog($message)
    {
        $pattern = '/(?=\[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\])/';
        $formatted = preg_replace($pattern, '<br>', trim($message));
        return $formatted;
    }
}
if (!function_exists('appendJobLog')) {
    function appendJobLog($contactId, $newMessage)
    {
        try {
            $log = \App\Models\SaveJobLog::firstOrCreate(['contact_id' => $contactId]);

            $timestamp = now()->format('Y-m-d H:i:s');
            $formattedMessage = "[$timestamp] " . $newMessage;

            // Append the message on a new line
            $existingMessage = $log->message ?? '';
            $log->message = $existingMessage === ''
                ? $formattedMessage
                : $existingMessage . "\n" . $formattedMessage;

            $log->save();
        } catch (\Throwable $e) {
            \Log::error('Failed to append job log', [
                'contact_id' => $contactId,
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString()
            ]);
        }
    }
}



if (! function_exists('getActions')) {
    /**
     * Generate action buttons for DataTables
     *
     * @param array $actions
     * @param string $route
     * @param int $id
     * @return string
     */
    function getActions(array $actions, string $route, int $id)
    {
        $html = '';

        if (isset($actions['edit']) && $actions['edit']) {
            $editUrl = route($route . '.edit', ['user' => $id]);
            $html .= '<a href="' . $editUrl . '" class="btn btn-sm btn-primary">Edit</a> ';
        }

        if (isset($actions['delete']) && $actions['delete']) {
            $deleteUrl = route($route . '.destroy', ['user' => $id]);
            $html .= '<a href="' . $deleteUrl . '" class="btn btn-sm btn-danger" onclick="return confirm(\'Are you sure?\')">Delete</a>';
        }

        return $html;
    }
}

//This Function give the user id of the Current logged in User
function isSuperAdmin()
{

    return (session('superadmin') && ! empty(session('superadmin'))) || is_role() == 'admin' || is_role() == 'company';
}

function customFields($customData, $agent)
{
    $noMatch=[];
    $customData = json_decode(base64_decode($customData), true);
    if (!is_array($customData)) {
        throw new \Exception("Invalid custom data format.");
    }

    $location_id = $customData['location']['id'] ?? null;
    $user = User::where('agent_id', $agent->id ?? '')->first();

    $locationId = $user ? $user->location_id : null;
    $location_id = $agent->destination_location ?? $customData['location']['id'] ?? null;

    $customFields = CustomField::select('cf_name', 'cf_id', 'cf_key')
        ->where('location_id', $location_id)
        ->get();

    $customFieldsMap = $customFields->pluck('cf_key', 'cf_name')->mapWithKeys(function ($value, $key) {
        return [trim($key) => trim($value)];
    })->toArray();

    $customFieldData = [];

    foreach ($customData as $key => $value) {
        $key = trim($key);

        if ($key === 'contact_id') {
            break;
        }

        if (array_key_exists($key, $customFieldsMap)) {
            $cfKey = $customFieldsMap[$key];
            $cfRecord = $customFields->firstWhere('cf_key', $cfKey);
            $cfId = $cfRecord ? $cfRecord->cf_id : null;
            $meta = is_array($value) && isset($value['meta']) ? (object) $value['meta'] : null;

            if ($meta) {
                $value['meta'] = $meta;
                $customFieldData[] = (object) [
                    'id' => $cfId,
                    'key' => str_replace('contact.', '', $cfKey),
                    'field_value' => is_array($value) ? (object) $value : [$value],
                ];
            } elseif (strpos(strtolower($key), 'pdf file') !== false || strpos(strtolower($key), 'selected plan image') !== false) {
                $customFieldData[] = (object) [
                    'id' => $cfId,
                    'key' => str_replace('contact.', '', $cfKey),
                    'field_value' => is_array($value) ? $value[0] : $value,
                ];
            } else {
                if(!is_null( $cfId)){
                    $customFieldData[] = (object) [
                        'id' => $cfId,
                        'key' => str_replace('contact.', '', $cfKey),
                        'field_value' => $value,
                    ];
                }
            }
        } else {
            $noMatch[] = $key;
          
        }
    }
    \Log::info("No match for custom field from the above data Checking below:", ['noMatch' => $noMatch]);
    if (!empty($customData['customData'])) {
        foreach ($customData['customData'] as $cdkey => $value) {
            $cdkey = trim($cdkey);
            // if(strpos($cdkey, 'Spouse') !== false ){
            //     \Log::info("Spouse found: " . $cdkey  . " value: " . json_encode($value));
            // }
            if (!(array_key_exists($cdkey, $customFieldsMap))) {
                continue;
            }
            $cfKey = $customFieldsMap[$cdkey];
            $cfRecord = $customFields->firstWhere('cf_key', $cfKey);
            $cfId = $cfRecord ? $cfRecord->cf_id : null;
            // if(strpos($cdkey, 'Spouse') !== false ){
            //     \Log::info("Spouse found: " . $cdkey  . " value: " . json_encode($value) . "  id: " . $cfId);
            // }
            if (is_null($cfId)) {
                continue;
            }

            $existingField = collect($customFieldData)->firstWhere('id', $cfId);
            // if(strpos($cdkey, 'Spouse') !== false ){
            //     \Log::info("Spouse found: " . $cdkey  . " value: " . json_encode($value) . "  Existing : " . json_encode($existingField));
            // }
            if ($existingField) {
                if (!is_null($existingField->field_value) && $existingField->field_value !== '') {
                    continue;
                } else {
                    $meta = is_array($value) && isset($value['meta']) ? (object) $value['meta'] : null;

                    if ($meta) {
                        $value['meta'] = $meta;
                        $existingField->field_value = is_array($value) ? (object) $value : [$value];
                    } elseif (strpos(strtolower($cdkey), 'pdf file') !== false || strpos(strtolower($cdkey), 'selected plan image') !== false) {
                        $existingField->field_value = is_array($value) ? $value[0] : $value;
                    } else {
                        $existingField->field_value = $value;
                    }
                    continue;
                }
            }

            $meta = is_array($value) && isset($value['meta']) ? (object) $value['meta'] : null;

            if ($meta) {
                $value['meta'] = $meta;
                $customFieldData[] = (object) [
                    'id' => $cfId,
                    'key' => str_replace('contact.', '', $cfKey),
                    'field_value' => is_array($value) ? (object) $value : [$value],
                ];
            } elseif (strpos(strtolower($cdkey), 'pdf file') !== false || strpos(strtolower($cdkey), 'selected plan image') !== false) {
                $customFieldData[] = (object) [
                    'id' => $cfId,
                    'key' => str_replace('contact.', '', $cfKey),
                    'field_value' => is_array($value) ? $value[0] : $value,
                ];
            } else {
                $customFieldData[] = (object) [
                    'id' => $cfId,
                    'key' => str_replace('contact.', '', $cfKey),
                    'field_value' => $value,
                ];
                // if(strpos($cdkey, 'Spouse') !== false ){
                //     \Log::info("Spouse found cf dtaa: " . json_encode($customFieldData) );
                // }
            }
        }
    }
        // \Log::info('Date of CF we Sent :  ' .json_encode($customFieldData) );
    return $customFieldData;
}


function login_id($id = "")
{
    if (! empty($id)) {
        return $id;
    }

    if (auth()->user()) {
        $id = auth()->user()->id;
    } elseif (session('uid')) {
        $id = session('uid');
    } elseif (Cache::has('user_ids321')) {
        $id = Cache::get('user_ids321');
    }

    return $id;
}

// function superAdmin()
// {
//    return 1;
// }
//This Function give the role of the Current logged in User
function is_role($user = null)
{
    if (! $user) {
        if (auth()->user()) {
            $user = auth()->user();
        }

    }
    if ($user) {
        if ($user->role == 0) {
            return 'superadmin';
        } elseif ($user->role == 1) {
            return 'admin';
        } elseif ($user->role == 2) {
            return 'company';
        } else {
            return 'user';
        }
    }
    return null;
}

function save_settings($key, $value = '', $userid = null)
{
    if (is_null($userid)) {
        $user_id = login_id();
    } else {
        $user_id = $userid;
    }
    // 'user_id' => $user_id;
    $setting = Setting::updateOrCreate(
        ['key' => $key],
        [
            'value'   => $value,
            'user_id' => $user_id,
            'key'     => $key,
        ]
    );
    return $setting;
}

function uploadFile($file, $path, $name)
{
    // Store the file in the 'public' disk and return the file path
    $name = $name . '.' . $file->getClientOriginalExtension();
    $file->storeAs('public/' . $path, $name); // Storing in the 'storage/app/public' directory

    // Return the relative path to the file
    return 'storage/' . $path . '/' . $name;
}
function getCarrierType()
{
    return
        [
        "Southern Farm Bureau Life Insurance Company",
        "Unified Life Insurance Company",
        "American National Life Insurance Company of Texas",
        "BEST Life",
        "GTECH Corporation",
        "Assurant Health",
        "Central Bank of Moberly",
        "Principal Life Insurance Company",
        "Guarantee Trust Life Insurance Company",
        "Prudential Insurance Company of America",
        "PacificSource Health Plans",
        "Perico Life Insurance Company",
        "RiverBridge Health, LLC.",
        "World Insurance Company",
        "N/A",
        "Nationwide Life Insurance Company",
        "Humana Insurance Company of Kentucky, Inc. ",
        "Aquent",
        "Humana",
        "Health Republic Insurance of New Jersey",
        "Union Fidelity Life Insurance Company",
        "Wilton Reassurance Company",
        "Transamerica Life Insurance Company",
        "Guardian",
        "CareFirst BlueChoice",
        "Central United Life Insurance Company",
        "The United States Life Ins. Co. in the City of New York",
        "Mid-West National Life Insurance Company of Tennessee",
        "Washington National Insurance Company",
        "Allied National, Inc.",
        "Freedom Life Insurance",
        "Delta Dental of New York, Inc.",
        "Thrivent Financial for Lutherans",
        "Seneca Foods Corporation",
        "Knights of Columbus",
        "The Union Labor Life Insurance Company",
        "American Republic Insurance Company",
        "Life of America",
        "West Virginia Health Cooperative",
        "Trustmark Insurance Company",
        "United of Omaha Life Insurance Company",
        "Oscar Health Plan of California",
        "National Foundation Life Insurance Company",
        "HealthMatters of Central Oregon",
        "Shelter Life Insurance",
        "United Teachers Associates",
        "Transamerica Financial Life Insurance Company",
        "First Allmerica Financial Life Ins. Co",
        "All Savers Insurance Company",
        "Dentegra Insurance Company",
        "State Farm Mutual Automobile Ins. Co.",
        "ACE Property and Casualty Insurance Company",
        "National Guardian Life Insurance Company",
        "Pekin Life Insurance Company",
        "Trustmark Life Insurance Company",
        "BCS Insurance Company",
        "New Era Life Insurance Company of the MidWest",
        "Celtic Insurance Company",
        "Health Net Life Insurance Company",
        "AMERICAN SYSTEMS",
        "American General Life Insurance Company",
        "WMI Mutual Insurance Company",
        "Health Net Health Plan of Oregon, Inc.",
        "Michigan Planners Inc",
        "UnitedHealthcare",
        "TransAmerica Premier Life Insurance",
        "Aetna",
        "Metropolitan Life Insurance Company",
        "UNICARE Life & Health Insurance Company",
        "First Commonwealth Limited Health Services Corporation of Michigan",
        "Federated Mutual Insurance Company",
        "American Income Life Insurance Co",
        "Liberty Mutual Insurance ",
        "ACCESS TO CARE HEALTH PLAN LLC",
        "American Progressive Life & Health Insurance Compa",
        "Harken Health Insurance Company",
        "MetroPlus Health Plan",
        "Independence American Ins Co",
        "The Cincinnati Life Insurance Company",
        "Premier Access Dental",
        "Reserve National Insurance Company",
        "Blue Cross Blue Shield of Wyoming",
        "Truitt Bros., Inc.",
        "Performance Inc",
        "Liberty National Life Insurance Co",
        "Christ Community Health Services Augusta Inc",
        "Reliance Standard Life Insurance Company",
        "United American Insurance Co",
        "Renaissance Dental",
        "Philadelphia American Life Insurance Company",
        "National Union Fire Insurance Company of Pittsburg",
        "Kansas City Life Insurance Company",
        "Blue Cross and Blue Shield of NC",
        "Family Health Network Marketplace",
        "PacifiCare Life and Health Insurance Co",
        "Access Health Colorado",
        "Meadow Valley Contractors, Inc.",
        "Frankenmuth Mutual Insurance Company",
        "The MEGA Life and Health Insurance Company",
        "Oscar Health Plan, Inc.",
        "Harvard Pilgrim Health Care",
        "CIGNA",
        "New Era Life Insurance Company",
        "The Ohio National Life Insurance Company",
        "Community Health Choice",
        "Blue Cross & Blue Shield of Mississippi",
        "Shelter Life Insurance Company",
        "TRUASSURE INSURANCE COMPANY",
        "AMERICAN FIDELITY ASSURANCE COMPANY",
        "Dental Service of Massachusetts, Inc.",
        "Illinois Mutual Life Insurance Company",
        "American Family Mutual Insurance Company",
        "Unimerica Insurance Company",
        "Globe Life and Accident Insurance Co",
        "DentaQuest- LA",
        "The Children's Hospital Corporation",
        "Tammy R Stouffer",
        "Humana Benefit Plan of Illinois, Inc.",
        "HCC Life Insurance Company",
        "Innovation Health Insurance Company",
        "ASL",
        "Freedom Life Insurance Company of America",
        "Cenral United Life Insurance Company",
        "United Concordia Insurance Company",
        "American National Insurance Company",
        "TruAssure Insurance Company",
        "Allianz Life Insurance Company of North America",
        "AMERICAN COMMUNITY MUTUAL INSURANCE COMPANY",
        "WESTERN GROCERS EMPLOYEE BENEFITS TRUST",
        "Aegis Security Insurance Company",
        "Union Labor Life Insurance Company",
        "DentaQuest Insurance Company, Inc.",
        "Wellfleet Insurance Company",
        "Health Plan of San Mateo",
        "DentaTrust/DentaSpan",
        "Standard Security Life",
        "UniCare Life & Health Insurance Company",
        "Bright HealthCare",
        "TexHealth Central Texas",
        "Sumitomo Machinery Corporation of America",
        "AXA Equitable Life Insurance Company",
        "Assurant Employee Benefits",
        "Nippon Life Benefits",
        "Madison National Life",
        "Medical Benefits Mutual Life Insurance",
        "Moore & Van Allen PLLC",
        "Golden Rule Insurance Company",
        "Delta Dental PPO",
        "Union Security Insurance Company",
        "lutheran medical center",
        "New York Life Insurance Co.",
        "Aetna Life Insurance Company",
        "American Heritage Life Insurance Company",
        "Partners & Napier, Inc",
        "Wisconsin Physicians Services Insurance Corporation",
        "Davidson College",
        "Bankers Reserve Life Insurance Co.",
        "AlwaysCare Benefits, Inc.",
        "Union Health Service, Inc.",
        "HealthNet of New Jersey Inc.",
        "Ameritas Life Insurance Corp.",
        "Standard Insurance Company",
        "American Medical Security Life Insurance Company",
        "Guardian ",
        "Central Bank of Oklahoma",
        "Time Insurance Company",
        "4 Ever Life Insurance Company",
        "Valmet, Inc.",
        "Mutual of Omaha Insurance Company",
        "SeeChange Health Insurance Company",
        "Anthem Blue Cross Life and Health Insurance Company, Inc.",
        "American Sentinel Insurance Company",
        "Wholesale",
        "WellSense Health Plan",
        "OptumRx Inc",
        "Health Advantage",
        "GMS Reinsurance Company, LTD",
        "LifeWise Assurance Company",
        "MAMSI Life and Health Insurance Company",
        "Cigna Healthcare",
        "3B Group, Inc.",
        "PacifiCare Life Assurance Company",
        "ACE American Insurance Company",
        "American General Life and Accident Insurance Company",
        "Alignment Health Plan",
        "Companion Life Insurance Company",
        "Everence Insurance Company",
        "Coventry Health Care",
        "Compcare Health Services Insurance Corporation",
        "Integon National Insurance Company",
        "First Medical Health Plan, Inc.",
        "CareSource",
        "Blue Cross Blue Shield of Vermont",
        "Puritan Life Insurance Company of America",
        "Centene Management Company",
        "UnitedHealthcare Insurance Company of New York",
        "HealthPlus of Michigan",
        "Medical Associates Health Plans",
        "American States Insurance Company",
        "UnitedHealthcare Insurance Company of the River Valley",
        "iDental from United Concordia",
        "Montefiore Insurance Company Inc.",
        "Lincoln Financial Group",
        "Denver Health Medical Plan, Inc.",
        "Community Care Network",
        "Horizon HMO",
        "DUVAL ASPHALT PRODUCTS INC",
        "BlueCross BlueShield of Tennessee",
        "Nippon Life Insurance Company of America",
        "HMO Colorado, Inc.",
        "UnitedHealthcare Insurance Company",
        "Standard Life and Accident Insurance Company",
        "UnitedHealthcare Life Insurance Company",
        "Nova Pathfinder Healthcare",
        "UNICARE Health Ins. Co. of the Midwest",
        "CGLIC",
        "Starr Indemnity & Liability Company",
        "The Pennsylvania Dental Corporation dba Delta Dental of Pennsylvania",
        "HPHC Insurance Company, Inc.",
        "Preferred Health Systems - PPO",
        "The Prudential Insurance Company of America",
        "National Foundation  Life Insurance",
        "MMM Healthcare, LLC.",
        "Family Health Hawaii mbs",
        "Amalgamated Life Insurance Company",
        "Argus Dental & Vision, Inc.",
        "Primewell Health Services of Mississippi",
        "Chorus Community Health Plans",
        "ERICO International Corporation",
        "Sierra Health and Life Insurance Company, Inc.",
        "Guardian Life Insurance Company of America",
        "Principal Life Insurance Company ",
        "Ambetter Health",
        "Ashers Chocolates",
        "General American Life Insurance Company",
        "UnitedHealthcare of the Mid-Atlantic, Inc.",
        "MetLife Insurance Company of Connecticut",
        "DeltaCare USA",
        "Bankers Life and Casualty Company",
        "Mitsubishi Motors North America, Inc-Manufacturing",
        "Cigna HealthCare of Georgia, Inc",
        "Flatiron Construction Corporation",
        "Hartford Life & Accident Insurance Company",
        "Security Life Insurance Company of America",
        "Blue Cross & Blue Shield of Rhode Island",
        "AmeriHealth HMO, Inc.",
        "Bankers Life Insurance Company",
        "Coventry",
        "Renaissance Life & Health Insurance Company of America",
        "Symetra Life Insurance Company",
        "Graphic Arts Benefit Corporation",
        "Blue Cross Blue Shield of Michigan Mutual Insurance Company ",
        "Dominion National",
        "Jefferson Life Insurance Company",
        "Piedmont Community HealthCare",
        "Lani Eko & Company",
        "The EPIC Life Insurance Company",
        "Oscar Insurance Company",
        "Central Bank of Boone County",
        "Consumers Life Insurance Company",
        "Friday Health Plans",
        "Medica Health Plans",
        "Roquette America, Inc.",
        "b.well",
        "Group Benefit Services",
        "Anthem Blue Cross and Blue Shield",
        "Coventry Health and Life Insurance Co.",
        "InHealth Mutual",
        "Delaware American Life Insurance Company",
        "Group Health Cooperative of Eau Claire",
        "UPMC Health Plan",
        "Twin City Pipe Trades Welfare Plan",
        "Farm Bureau Health Plans",
        "ASH Insurance",
        "Pan-American Life Insurance Company ",
        "Prominence Health Plan",
        "DentegraStar",
        "PHP or Physicians Health Plan",
        "Oscar Insurance Company of Illinois, Inc",
        "Florida Blue (BlueCross BlueShield FL)",
        "UHC New England Inc.",
        "UnitedHealthOne",
        "DentaQuest Washington",
        "HLAN",
        "Fidelity Life Association",
        "SchoolCare",
        "Delta Dental of the District of Columbia",
        "Aflac",
        "AmeriHealth Caritas Next",
        "Matthew Thornton Health Plan, Inc.",
        "Humana Insurance Company",
        "Sharecare, Inc.",
        "Healthy Alliance Life Insurance Company",
        "BEST Life and Health Insurance Company",
        "Premier Access Insurance Company",
        "Delta Dental",
        "Moda Health Plan, Inc.",
        "Reliance Standard Life Insurance Company ",
        "Ambetter from WellCare of New Jersey",
        "Pan-American Life Insurance Company",
        "Independent Health Benefits Corporation",
        "Altus Dental Insurance Company, Inc.",
        "Healthy Workers",
        "Molina Healthcare",
        "Trilogy Health Insurance, Inc.",
        "The Ohio State Life Insurance Company",
        "UnitedHealthcare Ins Co of Ohio",
        "DentaTrust ",
        "HealthPlus Partners, Inc.",
        "Securian Dental Plans",
        "Institute for Defense Analyses",
        "HMSA",
        "Assurity Life Insurance Company",
        "Blue Cross and Blue Shield of Kansas, Inc.",
        "Community Health Plan of Washington",
        "Aetna CVS Health",
        "New York Life Insurance Company",
        "Dental Care Plus, Inc.",
        "MetLife",
        "The Chesapeake Life Insurance Company",
        "HM Life Insurance Company",
        "Delta Dental ",
        "Sterling Life Insurance",
        "Aetna HealthAssurance Pennsylvania, Inc.",
        "MediExcel Health Plan",
        "National Foundation Life Insurance",
        "Trex Company, Inc",
        "KPS Health Plans",
        "Community Health Options",
        "IMC Manager, LLC",
        "Mass General Brigham Health Plan Select",
        "American Progressive Life & Health Insurance Company of New York",
        "Mid-West National Life Insurance Company of Tennes",
        "Tufts Associated Health Maintenance Organization, Inc.",
        "HMO Louisiana",
        "Perennial Advantage",
        "HealthKeepers, Inc.",
        "Auxilio Platino, Inc.",
        "Jefferson Health Plans",
        "Cigna Worldwide Insurance Company",
        "Premera Blue Cross HMO",
        "Whiting Oil and Gas Corporation",
        "Coventry Health and Life - TNARMS",
        "Rush",
        "AvMed",
        "Tufts Insurance Company",
        "EnerSys Delaware Inc",
        "HealthSpan Integrated Care",
        "Health Alliance",
        "HealthPartners",
        "Blue Cross Blue Shield of NC",
        "Medica",
        "Allstate Benefits",
        "McLaren Health Plan",
        "Nationcare ",
        "Scripps Health Plan",
        "Colorado Healthop",
        "Troy Construction, LLC",
        "Sentara Health Plans",
        "Welborn Health Plans",
        "Humana Health Plan",
        "O'Hara Corporation",
        "True Textiles, Inc",
        "University of Michigan Health Plan",
        "National Guardian Life Insurance",
        "ADVANTAGE Health Solutions, Inc",
        "TakeCare Insurance Company, Inc.",
        "EmblemHealth",
        "Kaiser Permanente",
        "WellCare of Kentucky",
        "Jayco Inc ",
        "Humana Insurance Co of Kentucky",
        "CAID Industries, Inc.",
        "The Horton Fruit Company",
        "ERC",
        "AAA Access Dental Plan of Texas, Inc.",
        "nHealth, Inc.",
        "Affiliated Foods Cooperative Inc",
        "Everence Association, Inc",
        "Standard Insurance Company ",
        "New Era Life Insurance Co of Midwest",
        "Standard Security Life Insurance Company of New York",
        "Remy International, Inc. ",
        "COMMUNITY HEALTH PLAN",
        "Advantica, Inc.",
        "Quartz",
        "EMI Health",
        "Delta Dental of Alaska",
        "World Corp Insurance Company",
        "Regence BlueCross BlueShield of Utah",
        "Talcott Resolution Life and Annuity Insurance Company",
        "MotivHealth Insurance Company",
        "Buckeye Health Plan Community Solutions, Inc.",
        "Lewis Marketing Group",
        "Babcock Power Inc.",
        "MD-Individual Practice Assocation, Inc",
        "Coventry Health and Life",
        "Delta Dental of Tennessee",
        "Geisinger Health Plan",
        "US Health and Life Insurance Company",
        "Willamette Dental of Idaho, Inc.",
        "Cariten Insurance Company",
        "United Health One",
        "Humana Insurance Company of New York, Inc",
        "United Health Care",
        "Silverton Health",
        "TL",
        "Wolverine Health Plans, Inc.",
        "NewBridge Bank",
        "MedMutual",
        "DentaQuest USA Insurance Company, Inc.",
        "BannerAetna",
        "Central Trust Bank",
        "Paramount Care of Michigan",
        "MCNA Dental",
        "CHC of CA",
        "Oscar Garden State Insurance Corporation",
        "All Savers Life Insurance Company of California",
        "American Medical Security Life Ins Co",
        "WEA Insurance Company",
        "Janet T Aillet",
        "Standard Life and Casualty Insurance Company",
        "UPMC Work Alliance",
        "Ameritas Life Insurance Corp. ",
        "Sun Life and Health Insurance Company (U.S.)",
        "Fresenius Medical Care- North America",
        "New West Health Services",
        "Family HealthCare Network",
        "MVP Health Care",
        "Employers Dental Services",
        "Blue Cross Blue Shield of Massachusetts",
        "Anthem Blue Cross",
        "Allianz Life Insurance Company of New York",
        "Anthem Insurance Companies, Inc.",
        "NEA Ret Health Trust",
        "iHeart Media, Inc.",
        "Conseco Life Insurance Company of Texas",
        "Madison National Life Insurance Company",
        "Protective Life Insurance Company",
        "Fidelis Care",
        "LifeMap Assurance Company",
        "PA SHPs",
        "Humana Health Plan. Inc.",
        "Dental Health Services",
        "United States Branch of the Sun Life Assurance Company of Canada",
        "alan",
        "Kaiser Foundation Health Plan of Washington Options, Inc.",
        "Delta Dental of South Dakota",
        "Georgia Health Marketplace LLC",
        "Wellmark Health Plan of Iowa, Inc.",
        "Paramount Dental",
        "Select Health",
        "BlueCross BlueShield of South Carolina",
        "United of Omaha Life Insurance Company ",
        "Capital Senior Living, Inc.",
        "First Health Life & Health Insurance Co.",
        "Small Group",
        "Corsicana Bedding Inc ",
        "UPMC Welfare Benefits Plan",
        "Ambetter from Nebraska Total Care",
        "Central Health Medicare Plan",
        "SafeGuard Health Plans, Inc., a California Corporation",
        "UnitedHealthcare Oxford",
        "The Goodyear Tire & Rubber Company",
        "Highmark Health Insurance Company",
        "MedCost Benefit Services LLC",
        "FirstCare Health Plans",
        "Oxford Health Plans (CT), Inc",
        "Coventry Health & Life Insurance Co.",
        "Liberty Mutual Insurance Company",
        "Connecticut General Life Insurance Co",
        "Premier HealthOne",
        "Health Net Insurance of New York, Inc.",
        "Cigna HealthCare of St. Louis, Inc",
        "Tokio Marine Pacific Insurance Limited",
        "Presbyterian Health Plan, Inc.",
        "Delta Dental of Minnesota",
        "HealthPartners Insurance Company",
        "Evolent Health LLC",
        "NetCare Life and Health Insurance Company",
        "HealthSpring of Tennessee, Inc.",
        "OHIOHEALTHY INSURANCE COMPANY",
        "UnitedHealthcare of Ohio, Inc",
        "Carolina Care Plan",
        "Holman Professional Counseling Centers",
        "All States Ag Parts, Inc",
        " \tHealth First Health Plans, Inc.",
        "Hometown Health Plan, Inc.",
        "Weight Watchers Intl Inc.",
        "Michigan MedChoices",
        "Capital BlueCross",
        "Kaiser Permanente Insurance Company",
        "Arches Health Plan",
        "JPS Industries, Inc.",
        "BlueCross BlueShield Kansas Solutions, Inc.",
        "Ambetter of Illinois",
        "AllCare Health Plan",
        "Seton Insurance Company",
        "Mesa Industries, Inc.",
        "Colorado Dental Service, Inc.",
        "AultCare Insurance Company",
        "Blossman Gas, Inc.",
        "Calnet, Inc",
        "Delta Dental of Arkansas",
        "Madison National Life Insurance Company, Inc.",
        "Health Alliance Connect",
        "METRO METALS NORTHWEST INC",
        "Delta Dental Plan of Oregon",
        "Renaissance Dental ",
        "CommunityCare HMO, Inc.",
        "Urban Retail Properties, LLC",
        "Protective Life Corporation",
        "Delta Dental of Indiana",
        "National Union Fire Insurance Company of Pittsburgh, Pa.",
        "Humana Health Plan of Ohio, Inc.",
        "Tufts Associated Health Maintenance Org",
        "Evonik Corporation",
        "Ambetter from Home State Health ",
        "Thirty-One Gifts",
        "City of Duncanville",
        "Priority Health",
        "Oscar Health Insurance",
        "Ambetter from Superior HealthPlan",
        "Community Insurance Company",
        "Managed Care of North America, Inc",
        "MedAssets Services, LLC",
        "Blue Cross and Blue Shield of Nebraska",
        "Bader Rutter",
        "MI SHPs",
        "UnitedHealthcare of Illinois Inc",
        "Enterprise Life Insurance Company",
        "Sick Benefit Fund Local 223",
        "Alliant Health Plans, Inc.",
        "FFE Issuer",
        "Everence Association, Inc., a fraternal benefit society",
        "Amerigroup",
        "Reid Hospital & Health Care Services",
        "Superior Dental Care, Inc.",
        "Delta Dental of Arizona",
        "Florida Combined Life",
        "Heartland Technology Group, Inc.",
        "Bankers Life and Casualty",
        "HEALTHCHOICE of MICHIGAN",
        "SafeGuard Dental MetLife",
        "United Healthcare",
        "Florida Blue HMO (a BlueCross BlueShield FL company)",
        "UNICARE Health Plans of Texas, Inc.",
        "United Skates of America, Inc.",
        "Sterling Life Insurance Co.",
        "Blue Cross Blue Shield of Montana",
        "Connecticut General Life Insurance Company",
        "United Concordia Life and Health Insurance Company",
        "Memorial Hermann Health Insurance Company, Inc.",
        "Curtis Lumber Company, Inc.",
        "Commercial Casualty Insurance Company",
        "Blue Cross and Blue Shield of Montana",
        "UnitedHealthcare Insurance Company of Ohio",
        "Dentcare Delivery Systems, Inc.",
        "Comstock Resources, Inc.",
        "Wisconsin Collaborative Insurance Company(Anthem BCBS)",
        "ZOOM+",
        "United Security Life and Health Insurance Company",
        "Scott & White Care Plans",
        "Kaiser Foundation Health Plan of Mid-Atlantic States, Inc.",
        "Avante Behavioral Health Plan",
        "University Health Services",
        "Sanford Health Plan",
        "Ambetter from CeltiCare Health Plan of MA",
        "DENCAP Dental Plans, Inc",
        "Highmark Blue Cross Blue Shield West Virginia",
        "Sirius America Insurance Company",
        "n/a",
        "Delta Dental of Virginia ",
        "Riverhead Building Supply",
        "Health Alliance Medical Plans, Inc.",
        "Southwest Life & Health Insurance Co.",
        "Arkansas Health Plan Co",
        "Independence Blue Cross",
        "Medica Insurance Company",
        "Dell Issuer2",
        "US Health and Life",
        "National Rifle Association of America, Inc.",
        "Antidote Health Plan of Ohio, Inc.",
        "Kaiser Permenante",
        "Employer Choice Insurance Company, Inc.",
        "Mountain Health CO-OP",
        "Jack in the Box Inc.",
        "Blue Cross Blue Shield of Minnesota",
        "American Family Insurance",
        "ATRIO Health Plans",
        "Valley Baptist Insurance Company",
        "Health Net Health Plan of Oregon, Inc",
        "Angle Health",
        "Ambetter from MHS Health WI",
        "Carpenters Health and Welfare Trust Fund for California",
        "Triple-S Salud Inc.",
        "Advantica Dental Benefits, Inc.",
        "PACE at Hudson Headwaters",
        "BCBSD, Inc.",
        "Priority Health Insurance Company, Inc",
        "Zeneca Inc.",
        "Select Medical Corporation Group Health Plan",
        "Samaritan Health Plans, Inc",
        "IU Health Plans",
        "Coventry Health Care of West Virginia, Inc.",
        "Blue Cross and Blue Shield of Texas",
        "Solstice Healthplans of Texas, Inc.",
        "SSM Health Plan",
        "TexHealth 3-Share Plan",
        "Highmark",
        "Care1st Helth Plan",
        "InStil Health",
        "Truli Health",
        "Wellmark Blue Cross and Blue Shield of Iowa              Wellmark Blue Cross and Blue Shield",
        "Palmetto Project",
        "Regal Life of America Insurance Company",
        "Solstice Healthplans of Arizona, Inc.",
        "HealthPartners, Inc.",
        "Pipe Fitters' Welfare Fund, Local 597",
        "Rampart Issuer",
        "Ambetter from Sunflower Health Plan",
        "HNE",
        "WellCare Health Insurance of Kentucky, Inc.",
        "Skip Hill & Associates LLC",
        "BridgeSpan Health Company",
        "Harbor Health Plan, Inc.",
        "Blue Cross and Blue Shield of Kansas City",
        "Imperial Insurance Companies, Inc.",
        "Delta Dental of Michigan",
        "DentaQuest Insurance Company Inc- OH",
        "Nevada Health CO-OP",
        "Kinder Morgan",
        "TexHealth El Paso",
        "Texas Health Resources Health Plan",
        "Minuteman Health",
        "NHIC",
        "Union Pacific Railroad Employes Health Systems",
        "Group Major Medical Plan",
        "HM Health Insurance Company",
        "West Coast Life Insurance Company",
        "MercyCare Health Plans",
        "Concert Health Plan Insurance Company",
        "HealthPlan Services",
        "Sur La Table, Inc.",
        "Blue Cross and Blue Shield of Illinois ",
        "ArchCare Advantage",
        "Health First Commercial Plans, Inc. ",
        "Group Administrators, Ltd.",
        "Tennant Company",
        "Highmark Blue Shield",
        "Blue Cross of Northeastern Pennsylvania",
        "Highmark Blue Shield of Northeastern New York",
        "Grand Valley Health Plan",
        "Delta Dental Plan of New Mexico",
        "HealthSpring of TN, Inc",
        "Loyal American Life Insurance Company",
        "Pekin LIfe Insurance Company",
        "Pittston Area School District",
        "Blue Cross Blue Shield of North Dakota",
        "Piedmont Community HealthCare HMO, Inc.",
        "Prominence HealthFirst of Texas, Inc.",
        "Willamette Dental of Washington, Inc.",
        "Morganite Industries, Inc.",
        "HAP",
        "Insurance Company of Scott & White",
        "UNICARE Health Plans of the Midwest, Inc",
        "Ambetter from Arkansas Health & Wellness",
        "Coventry Health Care Of Kansas Inc",
        "SummaCare Inc",
        "MAMSI  Life and Health Insurance Company",
        "Mountain Health Co-Op",
        "Security Health Plan",
        "Tianna Marrow",
        "Health Alliance Northwest ",
        "Premera Blue Cross Blue Shield of Alaska",
        "Dean Health Plan",
        "LifeWise Health Plan of Washington",
        "Scott and White Health Plan",
        "UnitedHealthcare of the Mid-Atlantic",
        "Canyon Insurance Group",
        "Highmark Blue Cross Blue Shield",
        "QCC Ins Company d/b/a AmeriHealth Ins Co",
        "Ambetter from Western Sky Community Care",
        "Health Net of Connecticut, Inc.",
        "Johns Manville",
        "First Commonwealth of Missouri, Inc.",
        "Thompson Construction Group",
        "WellCare of New York",
        "ElderONE",
        "Conseco Life Insurance Company",
        "Uniformed Firefighters Association",
        "Essence Healthcare, Inc",
        "Highmark Western and Northeastern New York",
        "Health Alliance Midwest, Inc.",
        "ASEA/AFSCME Local 52 Health Benefits Trust",
        "DSM USA Insurance Company Inc",
        "Access Dental",
        "CareFirst BlueCross BlueShield",
        "Texas Guaranteed Student Loan Corporation",
        "HAP CareSource",
        "GF Insurance, LLC",
        "Lake Hospital System, Inc. dba Lake Health",
        "Oscar Insurance Company of Florida",
        "Baptist Health Plan, Inc.",
        "Oxford Health Insurance, Inc.",
        "Baylor Scott and White Health Plan",
        "Engineered Machined Products",
        "Delta Dental of Missouri",
        "OptumRx, Inc.",
        "MS SHPs",
        "CHC of NJ",
        "Anthem HP, LLC",
        "Hometown Health Plan",
        "Southern Mgmt Corp",
        "FL SHPs",
        "Mass General Brigham Health Plan",
        "American Medical Security Life Ins CO",
        "Allina Health and Aetna Insurance Company",
        "Memorial Hermann Health Plan, Inc",
        "CrestPoint Health Insurance Company",
        "FirstCare PPO",
        "ING Life Insurance and Annuity Company",
        "Coventry Health Care of the Carolinas, Inc.",
        "Renaissance Health Insurance Company of New York",
        "Apex Tool Group, LLC",
        "Consumers Mutual Insurance of Michigan",
        "Cigna Health and Life Insurance Company",
        "South Sanpete School District",
        "Humana Health Plan, Inc.",
        "The Wornick Company",
        "Woodhouse Ford, Inc.",
        "Allegiance Life & Health Insurance, Inc.",
        "Driscoll Health System",
        "University of Utah Health Plans",
        "Managed Health Network,  A California Corporation",
        "Philadelphia American Life Insurance Co",
        "Oscar",
        "Dentegra Insurance Company of New England",
        "True Health New Mexico",
        "Garrett County Memorial Hospital",
        "The Guardian Life Insurance Company of America",
        "HBD Industries, Inc.",
        "UVA Darden School Foundation",
        "Nevada Dental Benefits, Ltd.",
        "CoOportunity Health",
        "Solstice of Illinois, Inc.",
        "Emphesys Insurance Company",
        "Solstice Benefits",
        "FirstCarolinaCare Insurance Company",
        "Delsure Health Insurance Inc",
        "Community Health Network of Washington",
        "Catamaran Insurance of Ohio, Inc.",
        "DentaQuest USA Insurance",
        "Crystal Run Health Insurance Company Inc.",
        "Medical Mutual",
        "MCS Life Insurance Company",
        "Pharmaceutical Strategies Group LLC",
        "Access Dental Plan of Utah, Inc",
        "DentaQuest Insurance Company Inc- TN",
        "The Dispatch Printing Company",
        "WellCare of North Carolina",
        "Access Dental Plan",
        "Lincoln Life & Annuity Company of New York",
        "Empire Blue Cross Blue Shield",
        "Sensient Technologies Corporation",
        "VSP Vision Care",
        "BIC Corporation",
        "Wellpoint",
        "Coventry Health Care of Nebraska Inc.",
        "Medical Services of America Employee Health Benefit Plan & Trust",
        "Health Matters of Central Oregon",
        "Alpha Dental of New Mexico, Inc.",
        "American Underwriters Life Insurance Company",
        "Regence Blue Shield of Idaho",
        "TOWER LIFE INSURANCE CO.",
        "Nation Care Small Group",
        "Ambetter from SilverSummit Healthplan",
        "Central Jersey Municipal Employee Benefits Fund",
        "Jack's Family Restaurants, Inc.",
        "Delta Dental of Nebraska",
        "DentaQuest Insurance Company Inc- IL",
        "Dewberry",
        "HealthPartners UnityPoint Health",
        "Providence Health Plan",
        "Oscar Insurance Corporation of Ohio",
        "Central Bank of the Ozarks",
        "Friday of Health Plans of Florida Inc",
        "West Penn Allegheny Health System",
        "First Commonwealth Limited Health Services Corporation",
        "Draeger Medical Systems, Inc",
        "Brilliance Health",
        "Hawaii Dental Service",
        "United Security",
        "Community First Health Plans",
        "DST Systems, Inc.",
        "Vail Rubber Works, Inc.",
        "Sidecar Health Insurance Company",
        "JMH Health Plan",
        "Blue Care",
        "Univera Healthcare",
        "AR SHPs",
        "Dallas Container Grop",
        "Anthem Health Plans of Maine, Inc.",
        "BD of Trustees Patriot Retirees VEBA  ",
        "Delta Dental of Idaho",
        "Coventry Health & Life Insurance Company",
        "Association Mutual Health Insurance Company",
        "Cook Childrens Health Plan",
        "ONECare",
        "Blue Cross and Blue Shield of Alabama",
        "Independence American Insurance Company",
        "Investors Life Insurance Company of North America",
        "Generations Healthcare",
        "Health Tradition Health Plan",
        "CaremarkPCS Health, LLC",
        "WellPoint",
        "Chinese Community Health Plan ",
        "Retailers Insurance Company",
        "Reser's Fine Foods, Inc.",
        "UnitedHealthcare of Alabama, Inc",
        "Aetna Health Inc. (a GA corp.)",
        "UnitedHealthcare Ins Co of Illinois",
        "Victory Packaging LP/GSC of CA",
        "Red Gate Software Inc",
        "Shiloh Industries, Inc.",
        "Excellus Health Plan Community Care, LLC.",
        "William A. Hazel, Inc.",
        "Employee Benefit Management Corp",
        "Metropolitan School District of Lawrence Township",
        "SimpleSaveRx",
        "SLV Health Access dba CarePoint",
        "Octave",
        "Inter-County Hospital  Plan",
        "Hamaspik, Inc.",
        "Hendricks Holding Company",
        "Southwest Service Life Insurance Company",
        "Humana ",
        "DentaQuest Mid-Atlantic, Inc.",
        "BKZ Benefits Group Inc.",
        "BCBSMN, Inc., dba Blue Cross and Blue Shield of Minnesota",
        "Great Southern Life Insurance Company",
        "UTMB",
        "Highmark Blue Cross Blue Shield of Western New York",
        "BlueChoice HealthPlan",
        "Pathoras Corporation",
        "PBT",
        "Florida Blue",
        "Premera Blue Cross",
        "Holly Foust",
        "Blue Cross Blue Shield of Wisconsin",
        "US HEALTH AND LIFE INSURANCE COMPANY",
        "Northeast Delta Dental",
        "Oscar Insurance Corporation of New Jersey",
        "Wellmark of South Dakota, Inc.",
        "WV SHPs",
        "Central Bank of Audrain County",
        "White Oak Management, Inc.",
        "Care1st Health Plan",
        "PHP",
        "Yucaipa-Calimesa Joint Unified School District",
        "OrthoPediatrics Corp",
        "Aspirus Arise Health Plan of Michigan, Inc.",
        "STALLINGS BROTHERS INC",
        "IEHP Covered",
        "Preferred Medical Plan",
        "ACCESS TO CARE HEALTH PLAN, LLC",
        "Health Net",
        "Circulo Health of Ohio, Inc.",
        "International Healthcare Services, Inc. ",
        "DentegraStar DHMO",
        "WPS Health Insurance",
        "CVS Health",
        "Cotton States Life Insurance Company",
        "SummaCare",
        "Fallon Health & Life Assurance Company",
        "Managed Dental Care of California",
        "Presbyterian Insurance Company, Inc.",
        "Highmark Choice Company",
        "Santa Cruz-Monterey-Merced  Managed Medical Care Commission",
        "IntelliBenefits Insurance Services, Inc.",
        "WINhealth Partners",
        "ND Banks Benefit Trust",
        "The Options Clearing Corporation",
        "Gilliatt",
        "TML Intergovernmental Employee Benefits Pool",
        "Coventry Health and Life ",
        "Chantal Mercier",
        "Keystone Health Plan Cental, a Capital BlueCross Company",
        "Blue Cross Blue Shield of Arizona",
        "Ambetter of Alabama",
        "UNICARE Health Insurance Company of the Midwest",
        "HANMI HEALTHCARE",
        "Blue Plus",
        "TX SHPs",
        "RU-Insured",
        "Santa Clara Family Health Plan",
        "JMM Test Issuer",
        "Columbia United Providers",
        "Taro Health Plan of Maine",
        "Interface, Inc.",
        "Humana Wisconsin Health Org. Ins. Corp.",
        "DYSART UNIFIED SCHOOL DISTRICT",
        "ESSENCE HEALTHCARE OF MINNESOTA CORPORATION",
        "Coordinated Care of Washington, Inc",
        "Baker Boy Bake Shop, Inc.",
        "Bluegrass Family Health, Inc.",
        "AETNA HEALTH INSURANCE COMPANY",
        "Orthopaedic & Spine Center of the Rockies",
        "American General Life and Accident",
        " UnitedHealthcare of the Midlands, Inc.",
        "Florida Health Care Plans",
        "Amerihealth Caritas Iowa",
        "CommunityCare Life & Health Insurance Company",
        "ASH Plans",
        "American Family Insurance Company",
        "Hawaii Medical Assurance Association",
        "NexDent Dental Plans, Inc.",
        "Ventura County Health Care Plan",
        "Delta Dental of North Carolina",
        "Sterling Investors Life Insurance Company",
        "UnitedHealthcare of North Carolina, Inc.",
        "AstraZeneca Pharmaceuticals LP",
        "Solstice Healthplans of Ohio, Inc.",
        "Affinity Health Plan, Inc.",
        "H&E Equipment Services",
        "BlueCross and Blue Shield of North Carolina",
        "Fogo de Chao",
        "MDC Holdings, Inc",
        "Deseret Mutual Insurance Company",
        "Anthem Blue Cross and Blue Sheld",
        "Eric Martinek",
        "QCC Insurance Company",
        "Alpha Dental of Alabama, Inc.",
        "Oscar Health Plan of Georgia",
        "Companion Life Insurance Company of NY",
        "Delta Dental of Washington",
        "Friday Health Plans of Virginia, Inc.",
        "Trimble Navigation Limited",
        "LIBERTY Dental Plan of Missouri, Inc.",
        "Dentegra PPO",
        "Lovelace Insurance Company",
        "Central Trust Company",
        "OB Issuer",
        "Physicians Plus Insurance Corporation",
        "Ambetter from Meridian",
        "Sun Life Assurance Company of Canada",
        "Ochsner Health Plan, Inc.",
        "Freelancers Insurance Company, Inc.",
        "Group Health Cooperative of South Central Wisconsin",
        "Mount Auburn Professional Services",
        "Ameritas Life Insurance Corp. Of NY",
        "Fallon Health and Life Assurance Co.",
        "DentaQuest Insurance Company-MO",
        "Taro Health Plan",
        "BAE Systems, Inc.",
        "Landmark U.S. Holdings, LLC",
        "Health Net of New York, Inc.",
        "Central Bank of Warrensburg",
        "DentaQuest Insurance Company, Inc. ",
        "Mid-Columbia Medical Center",
        "Health Choice Arizona Inc",
        "Tufts Health Public Plans Inc.",
        "THP Insurance Company",
        "MCS ADVANTAGE, INC.",
        "SAMBA Health Benefit Plan",
        "NA",
        "AMY JOHNSTON",
        "SAF-HOLLAND, Inc.",
        "CBIZ",
        "Parkland Community Health Plan",
        "Testing -UB",
        "Willamette Dental Group",
        "NORTH BAY FORD",
        "Paramount Care, Inc.",
        "Avera Health Plans",
        "Delta Dental of Illinois",
        "Bear River Mental Health Services, Inc.",
        "Standard Security Life Insurance Company of New Yo",
        "Meritus Health Partners",
        "UnitedHealthcare of New England Inc.",
        "Doskocil Manufacturing Company, Inc",
        "Citrus Health Care, Inc.",
        "Pacific Union College",
        "Inovalon, Inc",
        "Humana Health Plan of Ohio",
        "Highmark Senior Health Company",
        "Healthfirst Insurance Company, Inc.",
        "Ryder Health Plan, Inc.",
        "HealthCare Options Inc.",
        "Blue Cross of Idaho",
        "Ambetter from Louisiana Healthcare Connections",
        "ISLAND HOME INSURANCE COMPANY",
        "Ambetter from Coordinated Care",
        "CCL Industries Corporation",
        "MDwise Marketplace",
        "Delta Dental of KY",
        "DAKOTACARE",
        "Andrew Larsen",
        "MasterCraft Boat Company",
        "KelseyCare Advantage",
        "Judith Verona",
        "Ambetter of Oklahoma",
        "John A Van Den Bosch Co",
        "UPMC Health Benefits, Inc.",
        "UnitedHealthcare of Oregon, Inc.",
        "Delta Dental of California",
        "Sanford Heart of America Health Plan",
        "Rocky Mountain Health Plans (RMHP)",
        "William Penn Life Insurance Company",
        "Commercial Travelers Mutual Insurance Company",
        "The Peoples Bank",
        "Community First",
        "Delta Dental of Iowa",
        "Blue Cross and Blue Shield of Georgia, Inc.",
        "United Healthcare Life Insurance Company",
        "Allegian Health Plans",
        "North American Insurance Co.",
        "Priority Partners Managed Care Organization",
        "Martin Resource Management Corporation",
        "Hi Tech Fasteners",
        "Martin's Super Markets Inc.",
        "Seaside Health Plan",
        "Ambetter Health of Delaware",
        "Cold Spring Granite Company",
        "Queen's HealthCare Plan",
        "Sutter Health Plan",
        "National Health Insurance Company",
        "Fort Knox Federal Credit Union",
        "Longevity Health Plan",
        "Talcott Resolution Life and Annuity Insurance COmpany",
        "Golden State Medicare Health Plan",
        "Coventry Health Care of Texas, Inc.",
        "The Berry Company, LLC",
        "Mercy Health Plans",
        "Health Plan of San Joaquin Joint Powers Authority",
        "Modine Manufacturing",
        "New Era Life Insurnace Company",
        "Consumers' Choice Health Plan",
        "Medical Benefits Mutual Life Insurance Co.",
        " UnitedHealthcare of New Mexico, Inc",
        "Phoenix Health Plans, Inc.",
        "Serva Group Health Plan",
        "Cumulus Media, Inc.",
        "Delta Dental Insurance Company",
        "Vorys Group Health Plan",
        "The Children's Clinic",
        "HealthPartners Administrators, Inc.",
        "Inter-County Health Plan",
        "Debbie Gee",
        "Bright HealthCare Employer",
        "The Benefit Group, Inc.",
        "Pan-American Life Insurance Company of Puerto Rico",
        "Suzuki Motor of America, Inc",
        "CHRISTUS Health Plan",
        "Public Service Enterprise Group Incorporated",
        "Cheyenne Newspapers,Inc",
        "UnitedHealthcare Texas CHIP",
        "Elevate by Denver Health Medical Plan",
        "Hamilton Company ",
        "Erika Ross",
        "Blue Care of Michigan",
        "Community Health Alliance",
        "Capital Health Plan",
        "Optimum Choice Inc.",
        "Nationwide Mutual Insurance Company",
        "Health Net of California, Inc",
        "Total Health Care USA, Inc.",
        "Louisiana Health Cooperative, Inc.",
        "Vantage Health Plan",
        "Kirby Corporation",
        "UNICARE Health Plans of the Midwest, Inc.",
        "HMO Missouri, Inc.",
        "Central Bancompany",
        "Florida Student Health Plan",
        "Alameda Alliance Joint Powers Authority",
        "Piedmont WellStar HealthPlans, Inc.",
        "The S/L/A/M Collaborative, Inc.",
        "LIBERTY Dental Plan of California, Inc.",
        "SIHO Marketplace",
        "State Farm Mutual Automobile Insurance Company",
        "Vaughan Transportation, Inc.",
        "IlliniCare Health",
        "Antidote Health Plan of Arizona, Inc.",
        "Aetna Health Insurance Company",
        "Prominence Preferred Health Insurance Company, Inc.",
        "Softheon, Inc.",
        "Hotel Employees Restaurant Employees Health Trust",
        "DentaQuest Insurance Company Inc",
        "DentaQuest Insurance Company, Inc.  ",
        "nippon life benefits",
        "Physicians Mutual",
        "Atlanta International Insurance Company",
        "Dental Care Plus, Inc",
        "Asuris Northwest Health",
        "Alpha Dental Programs, Inc.",
        "UnitedHealthcare of Kentucky, Ltd.",
        "Solstice Healthplans of Colorado, Inc.",
        "Serventy Insurance Company, Inc.",
        "Oscar Health Plan of North Carolina, Inc",
        "The Toro Company",
        "Anthem Health Plans, Inc.",
        "USAble Life Group Health",
        "CA SHPs",
        "Advantica Insurance Company",
        "Ambetter of Tennessee",
        "Health Choice Insurance Co.",
        "PMC Medicare Choice LLC.",
        "Blue Shield of California",
        "ArchCare Senior Life",
        "So Cal Transport",
        "Banyan Community Health Center",
        "Independent Health Association, Inc",
        "CenCal Health",
        "TMI Hospitality",
        "UnitedHealthcare Benefits of Texas, Inc.",
        "Ceridian",
        "Pace Industries",
        "Imperial Health Plan of California, Inc.",
        "Ambetter from Peach State Health Plan",
        "Dresser, Inc.",
        "SC SHPs",
        "Brocade Communications Systems Inc.",
        "HD Supply",
        "Regence BlueCross BlueShield Of Oregon",
        "Blue Cross and Blue Shield of Oklahoma",
        "G6 Hospitality LLC",
        "Health Republic Insurance of New York",
        "Nationla Guardian Life Insurance Company",
        "Sentara Commercial Health Plans Of North Carolina Inc.",
        "Coast Aluminum and Architectural, Inc",
        "City of Lakeland",
        "Sendero Health Plans, Local Nonprofit",
        "North America Administrators, LP",
        "Ambetter from WellCare of Kentucky",
        "CHRISTUS Health Plan ",
        "Jefferson Bank",
        "Independence Hospital Indemnity Plan, Inc.",
        "Wellmark Blue Cross Blue Shield of Iowa",
        "United Securty",
        "Geisinger Indemnity Insurance Company",
        "Evergreen Health Cooperative, Inc.",
        "BlueCross BlueShield of Tennessee, Inc.",
        "Teresa Shaw",
        "QualChoice",
        "Ansaldo STS USA",
        "Delta County Memorial Hospital",
        "John Alden Life Insurance Company",
        "The Health Plan",
        "Cigna Healthcare of South Carolina",
        "United Food and Commercial Workers Union Local 227",
        "First Choice Next",
        "Niagara Life and Health Insurance Company",
        "Dell Childrens Health Plan",
        "Health Resources, Inc.",
        "Estes Express Lines",
        "CareSource Tennessee Co.",
        "Mitsui & Co. (U.S.A.), Inc. ",
        "DE SHPs",
        "Companion Life Insurance Company of California",
        " Moda Health Plan, Inc.",
        "Crystal Run Health Plan LLC",
        "CarePoint Insurance Company",
        "Flagship Health Systems, Inc.",
        "Oscar Insurance Corporation",
        "Paramount",
        "DSM USA Insurance Company",
        "Wellmark Value Health Plan, Inc.",
        "Preferred Health Plan, Inc.",
        "Delta Dental of Rhode Island",
        "McLaren Health Plan Community",
        "Howard Baer Inc",
        "Align Senior Care",
        "MPG Operations, LLC",
        "ConnectiCare, Inc.",
        "Woori America Bank",
        "Arkansas Blue Cross and Blue Shield",
        "Concorde Battery Corporation",
        "Texas Health + Aetna Health Insurance Company",
        "Argus Dental",
        "Anthem Blue Cross Blue Shield of Maine",
        "Blue Cross and Blue Shield of New Mexico ",
        "Memorial Hermann Commercial Health Plan",
        "McLaren Health Plan Insurance Company",
        "Geisinger Quality Options, Inc.",
        "Friday Health Plans of Missouri Insurance Company, Inc.",
        "Covered California",
        "Ambetter from NH Healthy Families",
        "Applied Industrial Technologies, Inc.",
        "Midwest Rubber Company",
        "Highmark Blue Cross Blue Shield Delaware",
        "OHIOHEALTHY HEALTH INSURING CORPORATION",
        "M&T Bank Corporation",
        "AS America",
        "Health First Government Plans, Inc.",
        "Curative",
        "Catawba Valley Medical Center",
        "Pam Duncan",
        " Coventry Health Care of Kansas, Inc. ",
        "TPA Issuer",
        "Regence BlueShield of Idaho, Inc.",
        "Southern New Jersey Regional Employee Benefits Fun",
        "Debra Peterson",
        "Talcott Resolution Life Insurance Company",
        "WinStar Farm, LLC",
        "ConnectiCare Benefits, Inc.",
        "Western Dental Services",
        "Health First Insurance, Inc.",
        "The Standard Life Insurance Company of New York",
        "Biformis",
        "Ambetter of North Carolina",
        "Delta Dental of South Carolina",
        "Debbie Connelly",
        "Blue Cross Blue Shield Healthcare Plan of Georgia, Inc.",
        "Banner Health and Aetna Health Insurance Company",
        "Rocky Mountain Hospital and Medical Service, Inc.",
        "Neighborhood Health Plan of Rhode Island",
        "United Dairy Inc",
        "AmeriHealth New Jersey",
        "Oxford Health Plans (NJ), Inc",
        "First Source Employee Management, Inc",
        "Catawba College",
        "Delta Dental of Oklahoma",
        "Upstate New York Engineers Health Plan",
        "Vanee Foods Company",
        "United  HealthCare Insurance Company",
        "Kentucky Health Cooperative",
        "Assurant Health ",
        "Health Alliance Midwest Inc.",
        "Mennonite General Hospital, Inc",
        "Moda Health",
        "Regence BlueCross BlueShield of Oregon",
        "ACN Group of California, Inc.",
        "Excellus Health Plan, Inc.",
        "Pilkington North America, Inc.",
        "Roman Catholic Church of the Diocese of Houma-Thib",
        "Sika Corporation",
        "Harken Health",
        "Al Warren Oil Co., Inc.",
        "SF large employer plan",
        "UnitedHealthcare Insurance Company of Illinois",
        "Engineered Machined Products Greenfield",
        "Partners Human Resource Co",
        "Teachers Protective Mutual Life",
        "Ambetter from Absolute Total Care",
        "KINGS HEALTH BROKERAGE",
        "Associated Mutual Insurance",
        "GEMCare Health Plan",
        "Molina Healthcare of Nevada, Inc.",
        "ABC AUTO PARTS LTD",
        "Friday Health Plans of Pennsylvania Inc",
        "Preferred Health Systems - HMO/POS",
        "Delta Dental of Wisconsin, Inc.",
        "CareSource Kansas, LLC.",
        "National Pharmaceutical Services",
        "Land of Lincoln Mutual Health Insurance Company",
        "Arise Health Plan",
        "CHC of FL",
        "CalCPA Group Insurance Trust",
        "Advantage Resourcing America, Inc.",
        "HealthAmerica Pennsylvania, Inc",
        "Vaagen Bros. Lumber, Inc.",
        "Rocky Mountain Health Plans",
        "Friday Health Plans of Tennessee Inc",
        "Virginia Premier Preferred",
        "Kaiser Foundation Health Plan of Washington",
        "Confederated Tribes of Siletz Indians COHO Benefit",
        "Empire Blue Cross Blue Shield ",
        "DSM MASSACHUSETTS INSURANCE COMPANY, Inc",
        "Moda Health Plan, Inc",
        "UHC FI",
        "Reserve Group Management Co",
        "Missouri Care, Inc.",
        "UCare Health Inc.",
        "ELAN",
        "Network Health",
        "www.nrinsurance.org",
        "HM Life Insurance Company of New York",
        "Delta Dental of Kansas",
        "Anthem Health Plans of Kentucky, Inc.",
        "USAble Mutual Insurance Company",
        "NY SHPs",
        "BlueCross BlueShield of Western New York, BlueShield of Northeastern New York",
        "Wisconsin Physicians Svc Insurance Corp",
        "Cox Health Systems HMO, Inc.",
        "Waters Corp",
        "CMD Health, Inc.",
        "KAISER PERMANENTE INSURANCE COMPANY",
        "Angela Storms",
        "North Shore-LIJ Insurance Company Inc",
        "ConnectiCare, Inc. & Affiliates",
        "Boston Medical Center HealthNet Plan, Inc.",
        "Athens Area Health Plan Select, Inc.",
        "HealthLink HMO, Inc.",
        "Fallon Community Health Plan",
        "NE SHPs",
        "Atlas Roofing Corporation",
        "United Agricultural Benefit Trust",
        "Cigna",
        "Healthfirst",
        "Alliant Health Plans",
        "Florida Health Solution HMO Company",
        "Delta Dental of Wyoming ",
        "Valley Health Plan",
        "Arkansas Blue Cross Blue Shield",
        "RD Offutt Company",
        "Trinity Health",
        "Zing Health, Inc.",
        "Schoenecker's Inc.",
        "MONY Life Insurance Company",
        "Vista360health",
        "NC SHPs",
        "WPS Health Plan",
        "PacificSource Community Health Plans",
        "ALAMEDA ALLIANCE FOR HEALTH",
        "Mid-Valley IPA Employee Benefit Trust",
        "Momentum Insurance Plans, Inc.",
        "LIBERTY Dental Plan of Florida, Inc.",
        "Conair Corporation",
        "Hometown Health Providers",
        "TAB PRODUCTS CO LLC",
        "GlobalHealth",
        "Solstice Health Insurance Company",
        "AccessTCA",
        "J & M",
        "UCare Minnesota",
        "LifeWise Health Plan of Oregon",
        "testWA",
        "Ambetter from PA Health & Wellness",
        "GOLDEN DENTAL PLANS, INC.",
        "Hometown Health Providers Insurance Company, Inc.",
        "Tufts Health Freedom Plan",
        "Central Bank of Branson",
        "LIBERTY Dental Plan",
        "Plan Medico SSBV",
        "Innovation Health Plan, Inc.",
        "Geisinger Quality Options",
        "Aspirus Health Plan",
        "Wilkes University",
        "Nationcare",
        "Delta Dental of Ohio",
        "Oscar Health Plan of South Carolina, Inc.",
        "Wisconsin Auto & Truck Dealers Insurance",
        "Pharmaceutical Product Development, LLC",
        "FamilyCare Health Plans, Inc.",
        "James M Pleasants Co",
        "LifeSecure Insurance Company",
        "Bright HealthCare from Bright Health Company of Arizona",
        "Talcott Resolution Life and Annuiyt Insurance Company",
        "Security Benefit Fund of the Uniformed Firefighter",
        "First Commonwealth Insurance Company ",
        "Brown Distributing",
        "You First by El Paso First Health Plans, Inc. ",
        "Common Ground Healthcare Cooperative",
        "WellAway Limited",
        "Centene Management Welfare Benefit Plan",
        "CommunityCare PPO",
        "Humana Benefit Plan of Ill.,Inc.",
        "Regence BlueShield",
        "Keystone VIP Choice",
        "Farmers Investment CO",
        "Wellmark Synergy Health, Inc.",
        "Dental Health Services, Inc.",
        "PreferredOne Insurance Company",
        "Dean Health Plan, Inc",
        "Health Net of Arizona, Inc",
        "First United American Life Insurance Company",
        "GA SHPs",
        "Dental Choice, Inc.",
        "NATIONAL GUARDIAN LIFE INSURANCE COMPANY",
        "UnitedHealthcare of Kentucky, Ltd",
        "QualChoice Life and Health Insurance Company, Inc.",
        "Connecticut Carpenters Health Fund",
        "Banner Life Insurance Company",
        "University of Arizona Health Plans - University Healthcare Marketplace",
        "ConnectiCare of Massachusetts, Inc.",
        "Companion Life Insurance Company ",
        "DentaQuest",
        "FirstFleet, Inc.",
        "Vaughan Foods, Inc.",
        "WCC Family Healthcare Plan",
        "Sentara Health Insurance Company",
        "Blue Cross and Blue Shield of Arizona, Inc.",
        "Bowlin Group, LL C",
        "Landauer, Inc.",
        "Community Care Health",
        "Ullico Casualty Company",
        "Kenneth Stockel",
        "Amedisys",
        "Aetna Health and Life Insurance Company",
        "MVP Health Services Corp.",
        "Highmark, Inc.",
        "Central Bank of St. Louis",
        "Avista Corporation",
        "North Jersey Municipal Employee Benefit Fund",
        "WTS International Inc.",
        "American Specialty Health Insurance Company",
        "GFSI, Inc",
        "CarePoint HMO, LLC",
        "The Finish Line, Inc.",
        "Anthem Health Plans of Virginia, Inc.",
        "Daimler Trucks North America",
        "Ambetter from Magnolia Health",
        "UnitedHealthcare of Texas",
        "North Carolina Dental Society Healthcare Plan",
        "ValueOptions of California, Inc.",
        "CareFirst of Maryland, Inc.",
        "Gundersen Health Plan, Inc.",
        "HealthyCT",
        "HealthAmerica Pennsylvania, Inc.",
        "State Law Enforcement Bargaining Council",
        "Ambetter from Arizona Complete Health ",
        "Romeo RIM, Inc.",
        "Horizon Blue Cross Blue Shield of New Jersey",
        "Retiree Welfare Plan ",
        "HealthSpan ",
        "Meritus Mutual Health Partners",
        "Arizona Pipeline Company",
        "St. Luke's Health Plan",
        "UCare Iowa",
        "Porex Corporation",
        "Sharp Health Plan",
        "CDPHP",
        "HMO Missouri, Inc.(Anthem BCBS)",
        "Healthplex Insurance Company, Inc.",
        "L,A, Care Health Plan",
        "Physicians Benefits Trust Life Insurance Company",
        "VIVA Health",
        "New Mexico Health Connections",
        "Retired Firefighters Security Benefit Fund of the ",
        "Aetna Health Inc.",
        "Healthplex Dental Services, Inc. ",
        "Harvard Pilgrim Health Care of New England, Inc.",
        "Western Health Advantage",
        "Empire Today",
        "HealthAssurance PA, Inc",
        "Health Partners of Philadelphia Inc.",
        "Loews Hotels at Universal Orlando",
        "Northwest Orthopaedic Specialists",
        "TexHealth Brazos Valley",
        "Ambetter from Magnolia Health ",
        "Massachusetts Institute of Technology",
        "Group Health Cooperative-SCW",
        "Bread Financial Payments, Inc.",
        "Von Maur, Inc.",
        "AL SHPs",
        "State of Tennessee",
        "Capital District Physicians Health Plan, Inc.",
        "ConnectiCare Insurance Company, Inc.",
        "Medica Health Plans of Florida, Inc",
        "Lori Latislaw",
        "Martin's Point Generations, LLC",
        "MAPFRE Life Insurance Company",
        "UHA",
        "Trillium Community Health Plan",
        "Atlantis Health Plan",
        "Westminster School",
        "Frank Miller Lumber Company, Inc.",
        "Union Bankers Insurance Company",
        "United States Fire Insurance Company",
        "Health Access Pueblo, Inc",
        "Cariten Health Plan, Inc.",
        "Health Plan of Nevada",
        "The Vermont Health Plan",
        "Health Republic Insurance Company",
        "Cox HealthPlans",
        "Sonepar Management",
        "Atlas Machine & Supply, Inc.",
        "Axis Insurance Company",
        "Anthem BC/BS",
        "U.S. Behavioral Health Plan, CA",
        "Gilbert Hospital",
        "Lovelace Health Plan",
        "Iowa Pacific Holdings, LLC",
        "Blue Cross and Blue Shield of Louisiana",
        "California Dental Network",
        "Central Bank of the Midwest",
        "PreferredOne Community Health Plan",
        "Cigna HealthCare of Arizona, Inc",
        "HealthSpring of Alabama, Inc.",
        "Qnova Health Inc.",
        "Melaleuca, Inc.",
        "USD 512 Shawnee Mission School District",
        "Rocky Mountain HMO",
        "DentaQuest Virginia, Inc.",
        "Elementis Global LLC",
        "Imperial Health Plan of the Southwest, Inc.",
        "Moreton ",
        "Blue Care Network of Michigan",
        "National Coatings & Supplies, Inc.",
        "Total Health Care, Inc.",
        "Schwartz Brothers Restaurants",
        "Central Bank of Sedalia",
        "PacificSource Health Plans HMO",
        "Oscar Health Plan of Pennsylvania, Inc.",
        "First Reliance Standard Life Insurance Company",
        "MYERS INDUSTRIES INC",
        "California Motor Dealers Employee BT",
        "Blue Cross and Blue Shield of Vermont",
        "Warehousemen's Health & Welfare Fund",
        "CommunityCare",
        "Test Insurance company",
        "Humana Health Insurance Co of FL, Inc.",
        "Central Mortgage Company",
        "Paramount Advantage",
        "Oregon's Health CO-OP",
        "CONTRA COSTA HEALTH PLAN",
        "eternalHealth",
        "Anthem Health Plans of New Hampshire, Inc.",
        "Lakeview Academy of Arts, Science and Technology",
        "Delta Dental of New Jersey",
        "Kaiser Foundation Health Plan of Georgia, Inc.",
        "Ambetter from Home State Health",
        "Bright HealthCare from Bright Health Insurance Company",
        "The Vermont Health Plan, LLC",
    ];
}

function saveStatusLog($sourceLocation, $campaignId, $agentId, $status = null, $reason = null)
{
    // Validate required fields
    if (empty($sourceLocation) || empty($campaignId) || empty($agentId)) {
        throw new InvalidArgumentException('Source location, campaign ID, and agent ID are required.');
    }

    // Create a new TrackLog entry
    return TrackLog::create([
        'source_location' => $sourceLocation,
        'campaign_id'     => $campaignId,
        'sent_to'         => $agentId,
        'status'          => $status,
        'reason'          => $reason,
    ]);
}
function CreateContactData($data, $agent = null, $campaign, $json = true, $dbcon = false)
{
    // Ensure $data is always an array
    if ($data instanceof \Illuminate\Support\Collection  || is_object($data)) {
        $data = $data->toArray();
    }
    $contactData = [
        'first_name'                                  => $data['first_name'] ?? null,
        'last_name'                                   => $data['last_name'] ?? null,
        'email'                                       => $data['email'] ?? null,
        'phone'                                       => $data['phone'] ?? null,
        'address1'                                    => $data['address1'] ?? null,
        'tags'                                        => isset($data['tags']) ? json_encode($data['tags']) : null, // Encode as JSON if it's an array
        'full_address'                                => $data['full_address'] ?? null,
        'country'                                     => $data['country'] ?? null,
        'source'                                      => $data['contact_source'] ?? null,
        'date_added'                                  => isset($data['date_created']) ? \Carbon\Carbon::parse($data['date_created']) : null,
        'city'                                        => $data['city'] ?? null,
        'state'                                       => $data['state'] ?? null,
        'postal_code'                                 => $data['postal_code'] ?? null,
        'location_id'                                 => $dbcon ? $data['location_id'] : $data['location']['id'] ?? null,
        'contact_id'                                  => $data['contact_id'] ?? null,
        'location'                                    => $dbcon ? $data['location'] : json_encode($data['location']) ?? null,
        'address'                                     => $dbcon ? $data['address'] : $data['location']['fullAddress'] ?? null,
        'user_id'                                     => $agent ? $agent->user_id : null,
        'agent_id'                                    => $agent ? $agent->id : null,
        'campaign_id'                                 => $campaign->id ?? null,
        // Custom data
        'address'                                     => $data['address'] ?? null,
        'city'                                        => $data['city'] ?? null,
        'state'                                       => $data['state'] ?? null,
        'postal_code'                                 => $data['postal_code'] ?? null,
        'trusted_form_ping_url'                       => $data['trusted_form_ping_url'] ?? null,
        'ip_address'                                  => $data['ip_address'] ?? null,
        'trusted_form_cert_url'                       => $data['trusted_form_cert_url'] ?? null,
        'your_gender'                                 => $data['your_gender?'] ?? null,
        'social_security'                             => $data['social_security'] ?? null,
        'marital_status'                              => $data['marital_status'] ?? null,
        'spouses_first_name'                          => $data['spouses_first_name'] ?? null,
        'spouses_last_name'                           => $data['spouses_last_name'] ?? null,
        //'spouse_gender' => $data['spouse_gende'] ?? null,
        'spouse_date_of_birth'                        => $data['spouse_date_of_birth'] ?? null,
        'do_you_want_to_enroll_spouse_as_well'        => $data['do_you_want_to_enroll_spouse_as_well'] ?? null,
        'spouse_ssn'                                  => $data['spouse_ssn'] ?? null,
        'tax_dependents_typically_children'           => $data['tax_dependents_typically_children'] ?? null,
        'number_of_tax_dependants_typically_children' => $data['number_of_tax_dependants_typically_children'] ?? null,
        'wish_to_enroll_your_dependents'              => $data['wish_to_enroll_your_dependents'] ?? null,
        'tax_dependants_date_of_births'               => $data['tax_dependants_date_of_births'] ?? null,
        'disqualify_lead'                             => $data['disqualify_lead'] ?? null,
        'company_name_if_self_employed'               => $data['company_name_if_self_employed'] ?? null,
        'projected_annual_income'                     => $data['projected_annual_income'] ?? null,
        'employment_status'                           => $data['employment_status'] ?? null,
        'signature'                                   => $data['signature'] ?? null,
        'my_signature'                                => $my_signature ?? null,
        'application_informatio_my_signature'         => $data['application_informatio_my_signature'] ?? null,
        'plan_name'                                   => $data['plan_name'] ?? null,
        'plan_carrier_name'                           => $data['plan_carrier_name'] ?? null,
        'plan_id'                                     => $data['plan_id'] ?? null,
        'plan_type'                                   => $data['plan_type'] ?? null,
        'brochure_url'                                => $data['brochure_url'] ?? null,
        'benefits_url'                                => $data['benefits_url'] ?? null,
        'date_of_birth'                               =>  isset($data['date_of_birth']) ? \Carbon\Carbon::parse($data['date_of_birth']) : null,
        'selected_plan_image'                         => $data['selected_plan_image'] ?? null,
        'contact_json'                                => $json ? $data['contact_json'] : base64_encode(json_encode($data)),
    ];
    return $contactData;
}
function state()
{
    return [
        'AL' => 'Alabama',
        'AK' => 'Alaska',
        'AZ' => 'Arizona',
        'AR' => 'Arkansas',
        'CA' => 'California',
        'CO' => 'Colorado',
        'CT' => 'Connecticut',
        'DE' => 'Delaware',
        'FL' => 'Florida',
        'GA' => 'Georgia',
        'HI' => 'Hawaii',
        'ID' => 'Idaho',
        'IL' => 'Illinois',
        'IN' => 'Indiana',
        'IA' => 'Iowa',
        'KS' => 'Kansas',
        'KY' => 'Kentucky',
        'LA' => 'Louisiana',
        'ME' => 'Maine',
        'MD' => 'Maryland',
        'MA' => 'Massachusetts',
        'MI' => 'Michigan',
        'MN' => 'Minnesota',
        'MS' => 'Mississippi',
        'MO' => 'Missouri',
        'MT' => 'Montana',
        'NE' => 'Nebraska',
        'NV' => 'Nevada',
        'NH' => 'New Hampshire',
        'NJ' => 'New Jersey',
        'NM' => 'New Mexico',
        'NY' => 'New York',
        'NC' => 'North Carolina',
        'ND' => 'North Dakota',
        'OH' => 'Ohio',
        'OK' => 'Oklahoma',
        'OR' => 'Oregon',
        'PA' => 'Pennsylvania',
        'RI' => 'Rhode Island',
        'SC' => 'South Carolina',
        'SD' => 'South Dakota',
        'TN' => 'Tennessee',
        'TX' => 'Texas',
        'UT' => 'Utah',
        'VT' => 'Vermont',
        'VA' => 'Virginia',
        'WA' => 'Washington',
        'WV' => 'West Virginia',
        'WI' => 'Wisconsin',
        'WY' => 'Wyoming',
    ];
}

function saveOrUpdateStateInDatabase($stateData)
{
    //dd($stateData);
    foreach ($stateData as $shortForm => $stateName) {
        //dd($shortForm);
        // Check if the state exists in the database
        $existingState = State::where('state', $stateName)->first();

        if ($existingState) {
            //dd($shortForm ,  $stateName);
            // Update the state if it exists
            $existingState->state      = $stateName;
            $existingState->short_form = $shortForm;
            $existingState->save();
            //dd($existingState);
        } else {
            //dd($shortForm ,  $stateName);
            // Create a new state if it does not exist
            State::create([
                'state'      => $stateName,
                'short_form' => $shortForm,
            ]);
            //dd($save);
        }
    }

    return response()->json([
        'success' => true,
        'message' => 'States have been saved or updated successfully.',
    ]);
}
// try {
//     if (! empty($customFieldData)) {
//         if (! empty($customData['customData'])) {
//             foreach ($customData['customData'] as $index => $dataValue) {
//                 $snakeCaseIndex = trim(Str::snake($index));

//                 foreach ($customFieldData as $field) {
//                     if ($field->key === $snakeCaseIndex && (is_null($field->field_value) || $field->field_value === '')) {
//                         if (! empty($dataValue)) {
//                             $field->field_value = $dataValue;
//                         }
//                     }
//                 }
//             }
//         }
//     }
// } catch (\Exception $e) {
//     Log::error('Error while processing customData: ' . $e->getMessage());
// }
